languageCode = 'en-us'
title = 'Eric Fritz'
baseurl = 'https://eric-fritz.com'
googleAnalytics = 'UA-24421005-1'
paginate = 20

[params]
  author = 'Eric Fritz'
  dateformat = '01.02.2006'
  index_page = '/articles/'
  resources_root = 'https://assets.eric-fritz.com'

[params.highlight]
  languages = ['go', 'java', 'cpp', 'dockerfile']

[params.social]
  email = 'eric@eric-fritz.com'
  github = 'efritz'

[[menu.main]]
  name = 'articles'
  identifier = 'articles'
  weight = 100
  url = '/articles/'

[[menu.main]]
  name = 'papers'
  identifier = 'papers'
  weight = 200
  url = '/papers/'

[[menu.main]]
  name = 'resume'
  identifier = 'resume'
  weight = 400
  url = '/resume/'
