languageCode = 'en-us'
title = 'Eric Fritz'
baseurl = 'https://blog-pqpe.onrender.com' # 'https://eric-fritz.com'
googleAnalytics = 'UA-24421005-1'
paginate = 1000

[permalinks]
  posts = '/:slug'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    codeFences = true
    style = "github"
    lineNos = true
    noClasses = true

[params]
  author = 'Eric Fritz'
  dateformat = '01.02.2006'
  index_page = '/articles/'
  resources_root = 'https://blog-pqpe.onrender.com/assets' # 'https://assets.eric-fritz.com'

[params.social]
  email = 'eric@eric-fritz.com'
  github = 'efritz'

[[menu.main]]
  name = 'articles'
  identifier = 'articles'
  weight = 100
  url = '/articles/'

[[menu.main]]
  name = 'papers'
  identifier = 'papers'
  weight = 200
  url = '/papers/'

[[menu.main]]
  name = 'resume'
  identifier = 'resume'
  weight = 400
  url = '/resume/'
