version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:12.7.0-stretch
    working_directory: ~/blog
  python:
    docker:
      - image: circleci/python:2.7-stretch
    working_directory: ~/blog

jobs:
  build:
    executor: node
    steps:
      - checkout
      - run:
          name: Download hugo
          command: |
            version='0.62.2'
            curl -L -o hugo.tar.gz "https://github.com/gohugoio/hugo/releases/download/v${version}/hugo_${version}_Linux-64bit.tar.gz"
            tar -xvzf hugo.tar.gz hugo
            sudo mv hugo /usr/local/bin/hugo
            rm hugo.tar.gz
      - run: hugo --minify
      - run: mkdir /tmp/workspace
      - persist_to_workspace:
          root: .
          paths:
            - public
            - bin

  deploy:
    executor: python
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install s3cmd
          command: |
            version='2.1.0'
            curl -L "https://github.com/s3tools/s3cmd/archive/refs/tags/v${version}.zip" -o s3cmd.zip
            unzip s3cmd.zip
            cd "s3cmd-${version}"
            sudo python setup.py install
            cd -
            rm -rf s3cmd.zip "s3cmd-${version}"
      - run:
          name: Deploy
          command: ./bin/deploy.sh
      - run:
          name: Bust cache
          command: ./bin/bust-cache.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
