name = "kabru"
license = "MIT"
licenselink = ""
description = ""
homepage = ""
tags = []
features = []
min_version = 0.14

[author]
  name = ""
  homepage = ""

[original]
  name = ""
  homepage = ""
  repo = ""
