name: Build and Deploy
on:
  push:
    branches:
      - master
      
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.61.0'

      - name: Build
        run: hugo --minify

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: ./bin/deploy.sh
        env:
          ACCESS_KEY: EFZG2XIFKGU5ZYI6SQ4V
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
