name: Build and Deploy
on:
  push:
    branches:
      - master
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.61.0'

      - name: Build
        run: hugo --minify

      - name: Deploy
        run: |
          sudo apt-get update
          sudo apt-get install ca-certificates git python python-setuptools
          git clone https://github.com/s3tools/s3cmd.git /tmp/s3cmd
          cd /tmp/s3cmd/
          python setup.py install
          cd -

          ./bin/deploy.sh
        env:
          ACCESS_KEY: EFZG2XIFKGU5ZYI6SQ4V
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
