name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        uses: actions/npm@4633da3702a5366129dca9d8cc3191476fc3433c
        with:
          args: install
      - name: Build
        uses: srt32/hugo-action@v0.0.3
      - name: Minify
        uses: actions/npm@4633da3702a5366129dca9d8cc3191476fc3433c
        with:
          args: run minify
      - name: Deploy
        run: ./bin/deploy.sh
        env:
          ACCESS_KEY: EFZG2XIFKGU5ZYI6SQ4V
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
